# This is a config for E2B sandbox template.
# You can use template ID (pgzzes7f1ztbdszadv6x) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("pgzzes7f1ztbdszadv6x") # Sync sandbox
# sandbox = await AsyncSandbox.create("pgzzes7f1ztbdszadv6x") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('pgzzes7f1ztbdszadv6x')

team_id = "f4da70b7-7410-4b42-9841-c84407c6b047"
start_cmd = "/root/.jupyter/start-up.sh"
dockerfile = "e2b.Dockerfile"
template_id = "pgzzes7f1ztbdszadv6x"
